INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '1F', '1', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '2F', '1', 2, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '3F', '1', 3, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '14F', '1', 4, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );	
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '15F', '1', 5, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '16F', '1', 6, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );	
	
INSERT INTO `iot_meeting`.`t_iot_config` ( `CON_VALUE`, `CON_TYPE`, `CON_ORDER`, `CREATE_TIME`, `UPDATE_TIME`, `BACK_COL1`, `BACK_COL2`, `BACK_COL3`, `BACK_COL4`, `BACK_COL5`, `BACK_COL6` )
VALUES
	( '会议大厅', '2', 1, NOW(), NOW(), NULL, NULL, NULL, NULL, NULL, NULL );