-- EXPLAIN
SELECT ROOM_ID,
(SELECT ROOM_NAME FROM t_call_service_room b WHERE b.ROOM_ID=t.ROOM_ID LIMIT 1) AS ROOM_NAME ,
(SELECT ROOM_IMG FROM t_call_service_room b WHERE b.ROOM_ID=t.ROOM_ID LIMIT 1) AS ROOM_IMG ,
MEETING_ID,
(SELECT MEET_NAME FROM t_call_service_meet b WHERE b.MEET_ID=t.MEETING_ID LIMIT 1) AS MEET_NAME ,
USER_ID,
(SELECT USER_NAME FROM t_call_service_user a WHERE a.USER_ID=t.USER_ID LIMIT 1) AS USER_NAME ,
CHAT_MSG,
CREATE_TIME,
FROM_UNIXTIME(CREATE_TIME) AS CHAT_TIME
FROM `t_call_service_chat` T
WHERE 1=1
AND ROOM_ID='7781705037676544' AND  T.CREATE_TIME<=UNIX_TIMESTAMP(NOW())
ORDER BY CREATE_TIME DESC
LIMIT 1;

-- EXPLAIN
SELECT 
USER_ID,
(SELECT USER_NAME FROM t_call_service_user a WHERE a.USER_ID=t.USER_ID LIMIT 1) AS USER_NAME ,
CHAT_MSG,
FROM_UNIXTIME(CREATE_TIME) AS CREATE_TIME
FROM `t_call_service_chat` T
WHERE 1=1
AND ROOM_ID='8646084058906624' AND  T.CREATE_TIME<=1693123963
ORDER BY CREATE_TIME DESC
LIMIT 6;


