server:
  servlet:
    context-path: /tablet-borrowed-service
  port: 8082
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  application:
    name: tablet-service
    # 数据库链接配置
  datasource:
    url: jdbc:nds://172.28.2.91:18800/v_iot_meeting?appname=app_iot_meeting
    username: calluser
    password: call123!@#
    driver-class-name: sgcc.nds.jdbc.driver.NdsDriver
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000
      # 用来检测连接是否有效的sql
      validation-query: select 'x'
      # 连接有效性检查的超时时间 30 秒
      validation-query-timeout: 30
      # 每次检查强制验证连接有效性
      keep-alive: true
      # 对于长时间不使用的连接强制关闭
      remove-abandoned: true
      # 设置获取连接出错时的自动重连次数
      connection-error-retry-attempts: 3
      # 设置获取连接时的重试次数，-1为不重试
      not-full-fimeout-retry-count: 3
      #重连间隔时间 单位毫秒
      acquire-retry-delay: 10000
# mybatis配置
mybatis:
  #  配置xml路径
  mapper-locations: "classpath:mapper/*Mapper.xml"
# logging
logging:
  config:
    classpath: log4j2.xml
  level:
    # root日志以WARN级别输出
    root: INFO
# redis数据库链接配置
redis:
  host: 172.28.5.134
  port: 17060
  timeout: 30000
  database: 1
  lockWatchdogTimeout: 30000
  connectionPoolSize: 24
  tryTime: 60000
  lockTime: 30000
  lockName: apply
  prefix: borrowed
#mqtt客户端配置
mqtt:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: mqtt_accept_client
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 60
  #设置会话心跳时间
  keepalive: 30
  defaultTopic: A2-206/206-RFID-UP
  dmqInfo:
         -/206-RFID-UP
  isOpen: true
  qos: 
     - 2
mqttprv:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: provider-id
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 60
  #设置会话心跳时间
  keepalive: 30
  defaultTopic: A2-206/206-RFID-UP
  dmqInfo:
         -/206-RFID-UP
  qos: 
     - 2
#会议预约系统接口配置
mtcofig:
  orgUserAd: http://d-nari.sgepri.sgcc.com.cn:90/hr-org-service/sysUser/queryEmp
  floorUrl: http://172.28.5.134:17010/api/meeting/sys-param-meta/query-sys-param-by-condition?group=FLOOR
  roomUrl: http://172.28.5.134:17010/api/meeting/mt-meeting-room/query?pageIndex={pageIndex}&pageSize={pageSize}&roomNameOrAddr=&cap=&floorId={floorId}
  mtinfoUrl: http://172.28.5.134:17010/api/meeting/statistics/?time={time}