server:
  servlet:
    context-path: /tablet-borrowed-service
  port: 8082
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  application:
    name: call-service
    # 数据库链接配置
  datasource:
    url: jdbc:nds://172.28.2.91:18800/v_wzh?appname=app_wzh
    username: wzh
    password: wzh123!@#
    driver-class-name: sgcc.nds.jdbc.driver.NdsDriver
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000
# mybatis配置
mybatis:
  #  配置xml路径
  mapper-locations: "classpath:mapper/*Mapper.xml"
# logging
logging:
  config:
    classpath: log4j2.xml
  level:
    # root日志以WARN级别输出
    root: INFO
#开启api文档
knife4j:
  enable: true
#mqtt客户端配置
mqtt:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: mqtt_accept_client
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 1000
  #设置会话心跳时间
  keepalive: 100
  defaultTopic: A2-227/227-wendu:A2-227/227-shidu
  dmqInfo:
         -/227-wendu
         -/227-shidu
  isOpen: true
  qos: 
     - 2
     - 2
mqttprv:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: provider-id
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 1000
  #设置会话心跳时间
  keepalive: 100
  defaultTopic: A2-228/228-power:A2-227/227-shidu
  dmqInfo:
         -/228-power
         -/227-shidu
  qos: 
     - 2
     - 2
#会议预约系统接口配置
mtcofig:
  orgUserAd: http://d-nari.sgepri.sgcc.com.cn:90/hr-org-service/sysUser/queryEmp
  floorUrl: http://172.27.32.70:17010/api/meeting/sys-param-meta/query-sys-param-by-condition?group=FLOOR
  roomUrl: http://172.27.32.70:17010/api/meeting/mt-meeting-room/query?pageIndex={pageIndex}&pageSize={pageSize}&roomNameOrAddr=&cap=&floorId={floorId}
  mtinfoUrl: http://172.27.32.70:17010/api/meeting/statistics/?time={time}