server:
  servlet:
    context-path: /tablet-borrowed-service
  port: 8082
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  application:
    name: tablet-borrowed-service
    # 数据库链接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iot_meeting?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 链接池初始化大小
      initial-size: 8
      # 最大活跃数
      max-active: 16
      # 最小空闲数
      min-idle: 1
      # 最大等待时间
      max-wait: 60000
# mybatis配置
mybatis:
  #  配置xml路径
  mapper-locations: "classpath:mapper/*Mapper.xml"
# logging
logging:
  config:
    classpath: log4j2.xml
  level:
    # root日志以WARN级别输出
    root: INFO
# redis数据库链接配置
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 30000
  database: 1
  lockWatchdogTimeout: 30000
  connectionPoolSize: 24
  tryTime: 60000
  lockTime: 30000
  lockName: apply
  prefix: borrowed
#mqtt客户端配置
mqtt:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: mqtt_accept_client
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 1000
  #设置会话心跳时间
  keepalive: 100
  defaultTopic: A2-206/206-RFID-UP
  dmqInfo:
         -/206-RFID-UP
  isOpen: true
  qos: 
     - 2
mqttprv:
  hostUrl: tcp://172.27.35.3:1883
  username: NARI
  password: Sgepri.1617
  clientid: provider-id
  cleanSession: true
  reconnect: true
  #连接超时
  timeout: 1000
  #设置会话心跳时间
  keepalive: 100
  defaultTopic: A2-206/206-RFID-UP
  dmqInfo:
         -/206-RFID-UP
  qos: 
     - 2
#会议预约系统接口配置
mtcofig:
  orgUserAd: http://d-nari.sgepri.sgcc.com.cn:90/hr-org-service/sysUser/queryEmp
  floorUrl: http://172.28.5.134:17010/api/meeting/sys-param-meta/query-sys-param-by-condition?group=FLOOR
  roomUrl: http://172.28.5.134:17010/api/meeting/mt-meeting-room/query?pageIndex={pageIndex}&pageSize={pageSize}&roomNameOrAddr=&cap=&floorId={floorId}
  mtinfoUrl: http://172.28.5.134:17010/api/meeting/statistics/?time={time}