---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tablet-service
  namespace: iot-dd
  labels:
    app: tablet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tablet-service
  template:
    metadata:
      labels:
        app: tablet-service
    spec:
      restartPolicy: Always
      hostNetwork: false
      nodeSelector: {}
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        image: 172.28.5.18:5000/iot/tabletservice:1.0.0.2.RELEASE
        imagePullPolicy: Always
        name: tablet-service
        resources:
          requests:
             cpu: 2
             memory: 4Gi            
        ports:
         - containerPort: 8082
           name: tablet-port            
---
apiVersion: v1
kind: Service
metadata:
  name: tablet-service
  namespace: iot-dd
  labels:
    app: tablet-service
spec:
  type: NodePort
  ports:
    - name: tablet-port
      port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 17040     
  selector:
    app: tablet-service